CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    name VARCHAR,
    given_name VARCHAR,
    family_name VARCHAR,
    picture TEXT,
    preferred_language VARCHAR,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
    user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    token VARCHAR NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);
